include ~/.config/kitty/colors.conf
# Font
font_size 20

map ctrl+shift+plus change_font_size all +1.0
map ctrl+shift+minus change font size all -1.0

# Background
background_opacity 0.4

mouse_hide_wait -1.0
