$mainMod = SUPER

# Screenshot a window
#bind = $mainMod, PRINT, exec, hyprshot -m window --clipboard-only
# Screenshot a monitor
bind = , PRINT, exec, hyprshot -m output --clipboard-only
# Screenshot a region
bind = $mainMod, PRINT, exec, hyprshot -m region --clipboard-only
