preload = ~/.config/hypr/arch.jpg

wallpaper {
    monitor = DP-2
    path = ~/.config/hypr/arch.jpg
    fit_mode = fill
} 

wallpaper {
    monitor = HDMI-A-2
    path = ~/.config/hypr/arch.jpg
    fit_mode = fill
}

ipc = off
splash = false
