workspace = 1,monitor:desc:KG251Q,bordersize:0,rounding:false,gapsout:0
workspace = 2,monitor:desc:KG251Q,bordersize:0,rounding:false.gapsout:0
workspace = 3,monitor:desc:PL2730H
workspace = 4,monitor:desc:PL2730H

windowrule = suppressevent maximize, class:.*

windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
