workspace = 1,monitor:HDMI-A-2,bordersize:0,rounding:false,gapsout:0
workspace = 2,monitor:HDMI-A-2,bordersize:0,rounding:false,gapsout:0
workspace = 3,monitor:DP-2
workspace = 4,monitor:DP-2

windowrule2 = suppressevent maximize, class:.*

windowrule2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
